language: haskell
ghc:
  - 7.6.3
script:
  - grunt test > testoutput || true
  - cat testoutput
  - 'cat testoutput | tr "\n" "\t" | grep -qv "ERROR"'

install:
  - cabal update
  - cabal install purescript --force-reinstalls
  - npm install bower grunt-cli -g
  - npm install
  - bower install
after_script:
  - rm testoutput
