language: node_js
node_js:
  - 0.10
script:
  - grunt test > testoutput && cat testoutput
  - cat testoutput | tr "\n" "\t" | grep -qv 'ERROR'

install:
  - sudo apt-get install cabal-install
  - cabal update
  - cabal install Cabal cabal-install
  - export PATH=~/.cabal/bin:$PATH
  - cabal install purescript --force-reinstalls
  - npm install bower grunt-cli -g
  - npm install
  - bower install
after_script:
  - rm testoutput
